name: Active Model OTP

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        gemfile: [rails_5.2, rails_6.0, rails_6.1, rails_7.0]
        ruby-version: [2.7, 3.0, 3.1, 3.2]
        exclude:
          - { gemfile: rails_5.2, ruby-version: 2.7 }
          - { gemfile: rails_5.2, ruby-version: 3.0 }
          - { gemfile: rails_5.2, ruby-version: 3.1 }
          - { gemfile: rails_5.2, ruby-version: 3.2 }
          - { gemfile: rails_6.0, ruby-version: 3.0 }
          - { gemfile: rails_6.0, ruby-version: 3.1 }
          - { gemfile: rails_6.0, ruby-version: 3.2 }
          - { gemfile: rails_6.1, ruby-version: 3.0 }
          - { gemfile: rails_6.1, ruby-version: 3.1 }
          - { gemfile: rails_6.1, ruby-version: 3.2 }

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
      - uses: actions/checkout@v2

      - name: Install Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: bundle install

      - name: Run tests with Ruby ${{ matrix.ruby-version }} and Gemfile ${{ matrix.gemfile }}
        run: bundle exec rake
