name: Active Model OTP

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        gemfile: [rails_4.2, rails_5.0, rails_5.1, rails_5.2, rails_6.0, rails_6.1]
        ruby-version: [2.3, 2.4, 2.5, 2.6, 2.7, 3.0]
        exclude:
          - { gemfile: rails_6.0, ruby-version: 2.3 }
          - { gemfile: rails_6.1, ruby-version: 2.3 }
          - { gemfile: rails_6.0, ruby-version: 2.4 }
          - { gemfile: rails_6.1, ruby-version: 2.4 }
          - { gemfile: rails_4.2, ruby-version: 2.7 }
          - { gemfile: rails_4.2, ruby-version: 3.0 }
          - { gemfile: rails_5.0, ruby-version: 3.0 }
          - { gemfile: rails_5.1, ruby-version: 3.0 }
          - { gemfile: rails_5.2, ruby-version: 3.0 }
    
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
      - uses: actions/checkout@v2

      - name: Install Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: bundle install

      - name: Run tests with Ruby ${{ matrix.ruby-version }} and Gemfile ${{ matrix.gemfile }}
        run: bundle exec rake
